MODEL:
  TYPE: dat
  NAME: dat_small
  DAT:
    img_size: 224
    patch_size: 4
    num_classes: 1
    expansion: 4
    dim_stem: 96
    dims: [96, 192, 384, 768]
    depths: [2, 2, 18, 2]
    stage_spec: [[L, S], [L, S], [L, D, L, D, L, D, L, D, L, D, L, D, L, D, L, D, L, D], [L, D]]
    heads: [3, 6, 12, 24]
    window_sizes: [7, 7, 7, 7] 
    groups: [-1, -1, 3, 6]
    use_pes: [False, False, True, True]
    dwc_pes: [False, False, False, False]
    strides: [-1, -1, 1, 1]
    sr_ratios: [-1, -1, -1, -1]
    offset_range_factor: [-1, -1, 2, 2]
    no_offs: [False, False, False, False]
    fixed_pes: [False, False, False, False]
    use_dwc_mlps: [False, False, False, False]
    use_conv_patches: False
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.3
    num_keypoints: 17
    aux_loss: false
    def_layers: 10

LOSS:
  # Class coefficient in the matching cost
  set_cost_class: 1.0
  # L1 box coefficient in the matching cost
  set_cost_bbox: 1.0
  # giou box coefficient in the matching cost
  set_cost_giou: 1.0
  # oks cost
  oks_cost: 1.0
  # kpt cost
  kpt_cost: 1.0

  # Loss
  mask_loss_coef: 1.0
  dice_loss_coef: 1.0
  cls_loss_coef: 1.0
  bbox_loss_coef: 1.0
  oks_loss_coef: 1.0
  kpt_loss_coef: 1.0
  giou_loss_coef: 1.0

  eos_coef: 0.1
  focal_loss: true
  focal_alpha: 0.25
  focal_gamma: 2
  masks: false

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 5e-4
  VAL_INTERVAL: 20
  
DATA:
  BATCH_SIZE: 16
  DATASET: posetrack18

  overflow_boxes: true
  masks: false

  img_transform:
    max_size: 1000
    val_width: 640
    size: [224,224]

  train_split: train
  train_split_json: train
  val_split: val
  val_split_json: val

  mot_path_train: /mnt/beegfs/work/ToyotaHPE/datasets/PoseTrack21/data
  mot_path_val: /mnt/beegfs/work/ToyotaHPE/datasets/PoseTrack21/data

SAVE_FREQ: 1

RESUME:
  # resume from checkpoint
  resume: ''
  ignore_mismatch: False
  resume_shift_neuron: False
  # resume optimization from checkpoint
  resume_optim: false
  # resume Visdom visualization
  resume_vis: false

VISDOM:
  # Visdom params
  # vis_server: http://localhost
  vis_server: 'http://aimagelab-srv-00'
  vis_port: 8097
  vis_and_log_interval: 5
  no_vis: false